### ISSUE TITLE
Update Angular 9->10

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#434]

**Comment by GerberI** [comment]
Also done:
- Some technical cleanup tasks in the build process (due to changes in the new angular compiler)
- Removed Opera from supported browsers (not supported by angular)
- Set supported browsers to versions since 2020

@afalenski 
Since it is an angular update please test the complete UI.
Also Angular 10 is outdated since dec2021. So we should update to 11 soon.

**Comment by GerberI** [comment]
@afalenski 
thanks for testing. 
Timings:
- Productive-Portal is always slightly faster then qa (optimized code). But would be nice to keep the data and test this again if we make a new release
- So i hoped the new angular version would make things faster...
- While uploading new data the portal has to wait until the server parsed and validated the excel sheet. This is very slow (to slow in my opinion). As long as the spinner is shown, the portal waits for the server. During performance update i optimized the code, to render the table while the portal is waiting for the server. So as long as the server code is slower than the browser rendering the loading performance can not be further optimized.
- So switching from FAQ to the table is a good measurement for client performance.
- Yes the waiting times has to be accepted. As long as we render thousands decorated and dynamic cells at ones it will always take some time for the browser to render them. As long as the portal is fluent after the table is initially rendered, i think all is fine.
- It might be useful to also show the spinner during table rendering (FAQ->table), so that the users gets not confused. So you can make a ticket for that.
