### ISSUE TITLE
Add table for previous orders 1

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#467]
As a MiBi-Portal user I would like to see orders when I click on the button "Bisherige Aufträge" (see mockup).

Research ticket: 
- Try out material UI table and MiBi-Portal table, use mock data in this ticket.
- Create table with fake data like in [mockup](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/6877ab03-d882-4d9c-9390-b9b0954cdd43)

- Text in column „Datum / Zeit“ is centered. 
- Text in column „Dateiname“ is left-aligned.
- Show scrollbar if list is longer than screen height.
- If the user hovers over a row with the mouse, the row turns light blue (like the colour from the second menu bar, RGB(186, 216, 233)) and the text changes to dark blue (RGB 0, 56, 105, #003869).

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-client/467?planning-poker) with ZenHub @birgitlewicki @GerberI @ruegenbfr

**Comment by GerberI** [comment]
My proposal for the new order-list view (part of the previous orders page):
- Used single-center-card layout for a form like feeling (selecting an order)
- Added a title (i hope i matched our "stupid" user feeling :)
- Used vanilla angular material table for consistent look and feel
- Added convenient scrolling behavior

Also done:
Added angular localization package:
- Used it for date formatting of the new order list
- later i will drop 2 problematic production libraries and use it to format the last-change date in the bottom-left corner too.

Refactored single-center-card-layout:
- For most forms in the app (login, register, home-page, ...) the content of the forms becomes now scroll-able instead of the whole form. So title and action buttons are sticky now.
- Reason: For most cases there is no difference for the user, for our new order list it became necessary because there might be more orders then the screen can display.
- Hint: There is a nasty fire-fox bug: The width gets miscalculated if a vertical scroll-bar appears. That's a common problem and i have no solution yet (only to alwasy show a scrollbar). For our actual purposes i think the bug can be ignored. (The bug was also there before the refactoring but not so present.)
- The title is smaller now. It is the default size of angular material, so i used this default.
- I also put the title in line with the rest of the content.

Refactored wall-of-text-layout:
- There should be no visible changes (faq, data-protection pages)

Refactored home-page:
- See single-center-card-layout
- Also i reduced the size of the app title a little bit

Refactored upload view:
- I switched to single center card layout here. I think it is more consistent, even more with the new order-list page. My reasoning: single-center-card for forms (user interactions) and wall-of-text for documents (faq and data-protection). Perhaps the home page should be changed to wall-of-text?

Added missing samples default route:
- /samples now navigates to /samples/editor. Alternatively we could navigate to the home-page?

**Comment by GerberI** [comment]
PS: There is a strange bug during switching from "Bisherige Aufträge" to another page. During the page transition animation the order list table gets emptied while still visible. I have, so far, no idea what the reason is. I assume it has something to do with the angular material table i used. My hope is that the bug disappears during further development ...

**Comment by afalenski** [comment]
- I like the card layout in persisted orders. On the upload page I do not like it. I find the centered headline with the thin blue line below much more elegant. But for consistency it is okay to leave it as it now is.
- There is no numbering column for persisted orders as in the mockup. But I like the tidy 2-column-look so let us leave out the numbering column.

**Comment by GerberI** [comment]
* Yes, i also think the old upload page looked better (or more elegant). But perhaps we are just used to the old look. The card layout looks more modern and fresh i think. We can ask the others in the next retro what they think and then change it again anyway. Perhaps we could use the wall of text look for home, upload and the new order-list as a new layout for main feature pages with a fixed header and only the content scrollable. Another option is to center the title for main features in the card layout to make it more present (or elegant).
* I've seen no sense in the numbering column, so i discarded it. Perhaps we have to add an id column later, if necessary.

**Comment by afalenski** [comment]
Overall look is great! Better than the mockup (which was just a transformation of the table for uploaded data)
- I cannot see whether the text in column „Datum / Zeit“ is centered, but it looks good the way it is.
- Text in column „Dateiname“ is left-aligned.
- Scrollbar appears if list is longer than browser window height.
- If the user hovers over a row with the mouse, the row turns light blue. BfR colours will be applied in the corporate identity ticket.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Firefox 91.10.0esr (64-Bit)
