### ISSUE TITLE
Rename text for spinner icon

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#475]
As a user having uploaded a data sheet and waiting for validation results I see the text "...alt" which makes me think I am using an old version of the MiBi-Portal.

Rename alt property of spinner icon to "Wird geladen . . .".

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-client/475?planning-poker) with ZenHub @bfrgottscma @birgitlewicki @GerberI @ruegenbfr

**Comment by GerberI** [comment]
I think the mentioned problem is due to missing google font for the upload icon in the background, see: ![image.png](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/9adb61e8-8648-4877-85fd-d361a4a28803).

@afalenski 
I recommend to close this ticket and prioritize #184 in our icebox instead.

**Comment by GerberI** [comment]
PS: Why is a 5 minute ticket like #184 in the icebox?

**Comment by afalenski** [comment]
Duplicate. mpc#184
