### ISSUE TITLE
Add program column to Excel v17 and catalog 328

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#539]
As a user I would like to officially state for which ZoMo programme I have uploaded sample data.

- Integrate a new column "Programm (Code aus AVV DatA-Kat-Nr. 328)" (see Einsendebogen v17) in the client between the columns "VVVO..." and "Bemerkung"
- Check against AVV DatA catalogue no. 328
- If code is not in catalogue no. 328, show error message "Ungültiger Code. Code ist nicht im AVV DatA-Katalog Nr. 328 enthalten."
- Check columns: If column "Kontroll-programm" contains code "70564|53075|" (meaning "Zoonosen-Monitoring") or if column "Kontroll-programm / Untersu-chungs-grund (Text)" contains the words "Zoonose" AND "Monitoring" (ignore case), show error message "Programm fehlt (Pflicht bei ZoMo)."

**Comment by afalenski** [comment]
- New column "Programm (Code aus AVV DatA-Kat-Nr. 328)" is present in the client between the columns "VVVO..." and "Bemerkung".
- New column is in PDF.
- New column is in Excel.
- New column is in Excel exported from the client.
- If code is not in catalogue no. 328, error message "Ungültiger Code. Code ist nicht im AVV DatA-Katalog Nr. 328 enthalten." is shown.
- If column "Kontroll-programm" contains code "70564|53075|" (meaning "Zoonosen-Monitoring") error message "Programm fehlt (Pflicht bei ZoMo)." is shown.
- If column "Kontroll-programm / Untersu-chungs-grund (Text)" contains the text "Zoonosen-Monitoring; Planprobe" error message "Programm fehlt (Pflicht bei ZoMo)." is shown.
**Bug:**
- If column "Kontroll-programm / Untersu-chungs-grund (Text)" contains the text "zoonose monitoring", no error message is shown.
- If column "Kontroll-programm / Untersu-chungs-grund (Text)" contains the text "zoonosen-monitoring", no error message is shown.
Please fix, as stated in the ticket text, e.g. by using RegEx. This is needed because some labs do not use AVV DatA and might only use free text in the column "Kontroll-programm / Untersu-chungs-grund (Text)".

Comment: Later, when the ZSP is included, an additional check will be implemented comparing uploaded data and the ZoMo programme.

**Comment by birgitlewicki** [comment]
Implemented check if a sample is a ZoMo sample or not as described:

If column "Kontroll-programm" contains code "70564|53075|" OR if column "Kontroll-programm / Untersu-chungs-grund (Text)" contains the words "zoonose" AND "monitoring" in a case insensitive manner the error message "Programm fehlt (Pflicht bei ZoMo)." is shown on the column "Programm"

**Comment by afalenski** [comment]
Kontrollprogramm text "zoonose" and "monitoring" is recognised, even in "zoonosewundervollmonitoring". Good!

**Bug:**
Still, the column "Programm" is not in the PDF. Will be done in a separate PDF ticket together with other PDF bugs.
This ticket is defined as done, although the programme is not shown everywhere where it should appear.
