### ISSUE TITLE
Fixing small issues

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#83]
As a mibi-portal user I'd like to see:

- Warning: "File is not the correct filetype: Files should be .xlsx" needs to be translated to German
- If data are uploaded and the page is left without sending the validated data I want to be warned always
- Fix typo: change 'Zuviele' to 'Zu viele' in toaster message
- The footer should have a white background

**Comment by birgitlewicki** [comment]
Point 1, 3 and 4: fixed

Point 2:
When data are uploaded and the user wants to leave the page via the menu options 'Upload', 'Abmelden'  and currently 'Anmelden' a corresponding warning dialog appears. The warning does not work for reloading the page or pressing the back or forward button. 

The 'Anmelden' behaviour will change when the ticket mps#25 will be implemented.

**Comment by afalenski** [comment]
Bullet point 1: OK
Bullet point 2: Not OK; if you klick "Mibi-Portal" data disappears without warning.
Bullet point 3: OK
Bullet point 4: Yes, the footer now has a white background and it looks much better. However, you still cannot see all the text on the starting page if the browser window height is below 600px because there is no scroll bar. Will there be a ticket for the scroll bar?

**Comment by birgitlewicki** [comment]
point 2: leaving the validate page needs now confirmation for every navigation possibilities, even for reloading and pressing the 'go back' button.
point 4: the minimal resolution is defined here: https://github.com/SiLeBAT/mibi-portal-resources/wiki/Browser-requirements. We still need to create a ticket for the scrollbar.
